-- 在庫管理アプリ：注文コーナー用テーブル
-- Supabase ダッシュボード → SQL Editor で実行

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  item_name text not null,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

create policy "orders_select" on public.orders for select using (true);
create policy "orders_insert" on public.orders for insert with check (true);
create policy "orders_delete" on public.orders for delete using (true);
